# Travis-CI Build for libadt
# see travis-ci.org for details

language: cpp
os: linux
dist: xenial

branches:
  only:
    - main

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test
